### ISSUE TITLE
Support new with params

### ISSUE THREAD

**Issue by jcblw** [mujo-code/puppeteer-headful#1]
This will help with versions of puppeteer and nodejs.

**Comment by jcblw** [comment]
Here is an example of what I think this syntax should look like. This allows the downloading of a specific version of node and chrome.

```yml
  - name: Test code
     uses: mujo-code/puppeteer-headful@v2
     with:
        node-version: '12.x'
        chrome-version: 'latest' 
     run: npm run test
```
