### ISSUE TITLE
Commands that are chained with && are not fully executed

### ISSUE THREAD

**Issue by dvdvdmt** [mujo-code/puppeteer-headful#114]
I've noticed that e2e tests in my project stopped working recently. 
Here is [my config](https://github.com/dvdvdmt/popup-tab-switcher/blob/34d39f483fa62742f45e2d0834a47c59fe9c5c08/.github/workflows/main.yml#L22-L27):
```
      - name: End-to-end tests
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm run build:e2e && npm run test:e2e
```
You can see that it has `npm run build:e2e && npm run test:e2e` command. The problem is that when I run [the action](https://github.com/dvdvdmt/popup-tab-switcher/runs/8283170151?check_suite_focus=true) only the `npm run build:e2e` is being executed and the `npm run test:e2e` produces no logs.
Could you please confirm if this is related to the puppeteer-headful action?
