### ISSUE TITLE
How to run it with docker-compose

### ISSUE THREAD

**Issue by ngohuytrieu** [mujo-code/puppeteer-headful#131]
Hi all,
I am trying to run jest-puppeteer tests with docker-compose in github actions
Here is my yml file:
```yml
jobs:
  test-e2e:
    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d

      - name: Run E2E Tests
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: docker exec -t app npm run test:e2e-admin

      - name: Tear down Docker Compose
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down
```

I got this error for above github action
```sh
/entrypoint.sh: 13: /entrypoint.sh: docker: not found
Running 'docker exec -t app npm run test:e2e-admin'!
```
