### ISSUE TITLE
Job fails with `Cannot open display`

### ISSUE THREAD

**Issue by stefanbuck** [mujo-code/puppeteer-headful#7]
Hi,

I want to use this GitHub action to test a chrome extension. I set `headless` to `false` according to the docs as well as the env var `PUPPETEER_EXEC_PATH`. However, the job is failing with the following error message.

```
(chrome:6378): Gtk-WARNING **: 18:44:16.028: cannot open display: 
Error: Failed to launch chrome!
```

It seems like `PUPPETEER_EXEC_PATH` is not defined. Any idea what is missing? I tried to find other repositories which are using this action, but nothing showed up in the GitHub search. I also set `PUPPETEER_EXEC_PATH` to `google-chrome-stable`, but it keeps failing

This is how my workflow file looks like

```yml
name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm run build
    - name: Run E2E
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    - run: npm run e2e
```

This is the related PR https://github.com/OctoLinker/OctoLinker/pull/662/
